services:
  noise-fundamentals:
    build:
      context: ./01-noise-fundamentals
    container_name: noise_fundamentals
    ports:
      - "5174:5174"
    volumes:
      - ./01-noise-fundamentals:/app
      - noise_fundamentals_modules:/app/node_modules
    networks:
      - app-network

  2d-terrain:
    build:
      context: ./02-2d-terrain
    container_name: 2d_terrain
    ports:
      - "5175:5175"
    volumes:
      - ./02-2d-terrain:/app
      - 2d_terrain_modules:/app/node_modules
    networks:
      - app-network

  tilemap-world:
    build:
      context: ./03-tilemap-world
    container_name: tilemap_world
    ports:
      - "5176:5176"
    volumes:
      - ./03-tilemap-world:/app
      - tilemap_world_modules:/app/node_modules
    networks:
      - app-network

  3d-voxel-terrain:
    build:
      context: ./04-3d-voxel-terrain
    container_name: 3d_voxel_terrain
    ports:
      - "5177:5177"
    volumes:
      - ./04-3d-voxel-terrain:/app
      - 3d_voxel_terrain_modules:/app/node_modules
    networks:
      - app-network

  biomes-and-structures:
    build:
      context: ./05-biomes-and-structures
    container_name: biomes_and_structures
    ports:
      - "5178:5178"
    volumes:
      - ./05-biomes-and-structures:/app
      - biomes_and_structures_modules:/app/node_modules
    networks:
      - app-network

  biome-blending:
    build:
      context: ./06-biome-blending
    container_name: biome_blending
    ports:
      - "5179:5179"
    volumes:
      - ./06-biome-blending:/app
      - biome_blending_modules:/app/node_modules
    networks:
      - app-network

  advanced-terrain:
    build:
      context: ./07-advanced-terrain
    container_name: advanced_terrain
    ports:
      - "5180:5180"
    volumes:
      - ./07-advanced-terrain:/app
      - advanced_terrain_modules:/app/node_modules
    networks:
      - app-network

  spline-terrain:
    build:
      context: ./08-spline-terrain
    container_name: spline_terrain
    ports:
      - "5181:5181"
    volumes:
      - ./08-spline-terrain:/app
      - spline_terrain_modules:/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: maestre-web_app-network

volumes:
  noise_fundamentals_modules:
  2d_terrain_modules:
  tilemap_world_modules:
  3d_voxel_terrain_modules:
  biomes_and_structures_modules:
  biome_blending_modules:
  advanced_terrain_modules:
  spline_terrain_modules:
